## Unit 03: Generators and Numpy Arrays

### 1) Generators

Generator functions allow you to declare a function that behaves like an iterator, i.e. it can be used in a for loop. 
#### Why would I prefer generators?
* Generators are memory-efficient because they only load the data needed to process the next value in the iterable. This allows them to perform operations on otherwise prohibitively large value ranges.So generators help you make lazy code.
* The simplification of code


A generator looks like this:
```python
def funktion_name(variable):
    yield iterative
```

Example of a basic generator:

In [ ]:
def double_numbers(iterable):
    print(iterable)
    for i in iterable:
        if i >= 10:
            return
        yield i + i

Now the generator can be used in a for loop:

In [ ]:
for i in double_numbers(range(1, 900000000)):
    print(i)

next() method:

In [ ]:
def example_generator():
    print("begin")
    for i in range(3):
        print("before yield", i)
        yield i
        print("after yield", i)
    print("end")
        
generator = example_generator()
next(generator)
print("-------")
next(generator)
print("-------")
next(generator)

Just as you can create a list comprehension, you can create generator comprehensions as well.

In [ ]:
values = (-x for x in [1,2,3,4,5])
for x in values:
    print(x)

You can also cast a generator comprehension directly to a list.

In [ ]:
values = (-x for x in [1,2,3,4,5])
generator_to_list = list(values)
print(generator_to_list)

### 2) Numpy Array advanced Indexing, Slicing and Subsetting 

In [2]:
import numpy as np

matrix = np.arange(4 * 5).reshape(4, 5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
matrix[[1,2,1],:] #first rows, then cols

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [4]:
matrix[[1,2,1],:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [ 5,  6,  7]])

In [5]:
matrix[[1,2,1],3]

array([ 8, 13,  8])

In [6]:
matrix[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [7]:
matrix[0:2,2:5]

array([[2, 3, 4],
       [7, 8, 9]])

You can index with lists and np.arrays:

In [8]:
numpy_array = np.array([2,3,1,0])

display(matrix[numpy_array])
display(matrix[numpy_array,numpy_array])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

array([12, 18,  6,  0])

Boolean Indexing:

In [11]:
array_a = np.array([1,2,3,6,1,4,1])
array_b = np.array([5,6,7,8,3,1,2])

In [13]:
# Only saves array_a at index where array_b == 1
boolean_array = (array_a == 1)
print(boolean_array)
print(array_b[boolean_array])

[ True False False False  True False  True]
[5 3 2]


In [15]:
array_b[array_a != 1]

array([6, 7, 8, 1])

In [16]:
array_a[array_b > 5]

array([2, 3, 6])

In [17]:
# numpy.all() Test whether all array elements along a given axis evaluate to True.
# True: every value in array is not 0
# False: at least one value in array is 0
combined_array = np.array([array_a, array_b, np.zeros(len(array_a))])

display(combined_array)
print(np.all(combined_array))
print(np.all(combined_array, axis=1)) # axis=1 looks at rows
print(np.all(combined_array, axis=0)) # axis=0 looks at cols

array([[ 1.,  2.,  3.,  6.,  1.,  4.,  1.],
       [ 5.,  6.,  7.,  8.,  3.,  1.,  2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

False
[ True  True False]
[False False False False False False False]


In [19]:
# working with boolean arrays example np.where()
print(np.where([[True, False], [False, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]]))
print(np.where([False, False, False, True, False]))
print(np.where(np.all(combined_array, axis=1)))

[[1 8]
 [7 4]]
(array([3], dtype=int64),)
(array([0, 1], dtype=int64),)
